{
 "title": "Block Exporter - Single Node",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "geth_net_listening{job=\"block\"}"
   }
  ]
 },
 "panels": [
  { "title": "System Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$instance\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU usage（5m）",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$instance\"} / (node_memory_MemTotal_bytes{instance=~\"$instance\"})))* 100"
    }
   ]
  },
  {
   "title": "System average loading",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}_1m"
    },
    {
     "expr": "node_load5{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}_5m"
    },
    {
     "expr": "node_load15{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}_15m"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bps", "label": "Upstream（-）/Downstream（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$instance',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "{{instance}}_{{device}}_in_Downstream"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$instance',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "{{instance}}_{{device}}_out_Upstream"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}_Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}_Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}_Available"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "iops", "label": "Read（-）/Write（+）I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"$instance\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=\"$instance\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_Write"
    }
   ]
  },
  {
   "title": "TCP connection status",
   "type": "graph",
   "description": "CurrEstab - The TCP connection volume which status is ESTABLISHED or CLOSE-WAIT \n\nActiveOpens - The average(1 min) TCP connection volume changed status from CLOSED to SYN_SENT\n\nPassiveOpens - The average(1 min) TCP connection volume changed status from LISTEN to SYN_RCVD\n\nTCP_alloc - The TCP connection volume allocated (Established & applied for sk_buff)\n\nTCP_inuse - The TCP connection volume which is in-used\n\nTCP_tw - The TCP connection volume which wait to be closed",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance='$instance'}",
     "legendFormat": "{{instance}}_ESTABLISHED"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance='$instance'}",
     "legendFormat": "{{instance}}_TCP_tw"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance='$instance'}[1m])",
     "legendFormat": "{{instance}}_ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance='$instance'}[1m])",
     "legendFormat": "{{instance}}_PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance='$instance'}",
     "legendFormat": "{{instance}}_TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~'$instance'}",
     "legendFormat": "{{instance}}_TCP_inuse"
    }
   ]
  },
  {
   "title": "Disk I/O Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "s", "label": "Read（-）/Write（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=\"$instance\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=\"$instance\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_Write"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$instance',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$instance',fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{instance}}：{{mountpoint}}"
    }
   ]
  },
  { "title": "Consensus Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Node Peer Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "geth_net_peer_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Transaction processed",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "geth_transaction_processed{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Pending Transactions",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 21 },
   "targets": [
    {
     "expr": "geth_txpool_status_pending{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Geth Network Connected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "geth_net_listening{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Latest Block",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "geth_latest_block{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Queued Transactions",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 27 },
   "targets": [
    {
     "expr": "geth_txpool_status_queued{instance=\"$instance\"}"
    }
   ]
  }
 ]
}