{
 "title": "Block Exporter - Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Common Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(geth_node_index{job=\"block\"}) by (instance)"
    },
    {
     "expr": "sum(geth_net_listening{job=\"block\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(geth_net_peer_count{job=\"block\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(geth_latest_block{job=\"block\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(geth_transaction_processed{job='block'}) by (instance)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(geth_txpool_status_pending{job='block'}) by (instance)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(tessera_send_private_transactions{job=\"tessera\"} or constellation_send_private_transactions{job=\"constellation\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(tessera_decrypted_private_transactions{job=\"tessera\"} or constellation_decrypted_private_transactions{job=\"constellation\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Latest Block Number",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(geth_latest_block{job=\"block\"})"
    }
   ]
  },
  {
   "title": "Block Latency (Block/min)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 10 },
   "targets": [
    {
     "expr": "max(rate(geth_latest_block{job=\"block\"}[1m]))*60",
     "legendFormat": "1 min"
    },
    {
     "expr": "max(rate(geth_latest_block{job=\"block\"}[5m]))*60",
     "legendFormat": "5 mins"
    },
    {
     "expr": "max(rate(geth_latest_block{job=\"block\"}[10m]))*60",
     "legendFormat": "10 mins"
    },
    {
     "expr": "max(rate(geth_latest_block{job=\"block\"}[10m]))*60",
     "legendFormat": "15 mins"
    }
   ]
  },
  {
   "title": "Block Number",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "geth_latest_block{job=\"block\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Max Transaction Processed",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(geth_transaction_processed{job=\"block\"})"
    }
   ]
  },
  {
   "title": "TPS (txs/sec)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 17 },
   "targets": [
    {
     "expr": "max(rate(geth_transaction_processed{job=\"block\"}[1m])) ",
     "legendFormat": "1 min"
    },
    {
     "expr": "max(rate(geth_transaction_processed{job=\"block\"}[5m])) ",
     "legendFormat": "5 mins"
    },
    {
     "expr": "max(rate(geth_transaction_processed{job=\"block\"}[10m])) ",
     "legendFormat": "10 mins "
    },
    {
     "expr": "max(rate(geth_transaction_processed{job=\"block\"}[15m])) ",
     "legendFormat": "15 mins "
    }
   ]
  },
  {
   "title": "Transactions processed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "geth_transaction_processed{job='block'}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Geth Network Connected",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_net_listening{job=\"block\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Pending Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "geth_txpool_status_pending{job='block'}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Node Peer Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_net_peer_count{job='block'}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Queued Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "geth_txpool_status_queued{job='block'}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Send Private Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(tessera_send_private_transactions{job=\"tessera\"} or constellation_send_private_transactions{job=\"constellation\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Received Private Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(tessera_decrypted_private_transactions{job=\"tessera\"} or constellation_decrypted_private_transactions{job=\"constellation\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Tessera Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tessera - Send private transactions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tessera_send_private_transactions{job=\"tessera\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Tessera - Receive private transactions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tessera_receive_private_transactions{job=\"tessera\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Tessera - Sent private transactions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tessera_sent_private_transactions{job=\"tessera\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Tessera - Decrypted private transactions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tessera_decrypted_private_transactions{job=\"tessera\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Tessera - Failed to decrypt private transactions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tessera_decrypt_failed_private_transactions{job=\"tessera\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Constellation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Constellation - Send private transactions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "constellation_send_private_transactions{job=\"constellation\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Constellation - Receive private transactions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "constellation_receive_private_transactions{job=\"constellation\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Constellation - Decrypted private transactions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "constellation_decrypted_private_transactions{job=\"constellation\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Constellation - Failed to decrypt private transactions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "constellation_decrypt_failed_private_transactions{job=\"constellation\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}