{
 "title": "Block-Exporter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "geth_net_listening{job='block'}"
   }
  ]
 },
 "panels": [
  {
   "title": "Geth Network Connected",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "geth_net_listening{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Geth Network Connected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "geth_net_listening{job=\"block\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Pending Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_txpool_status_pending{job='block'}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Pending Transactions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "geth_txpool_status_pending{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Node Peer Count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "geth_net_peer_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Node Peer Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_net_peer_count{job='block'}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Queued Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_txpool_status_queued{job='block'}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Queued Transactions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "targets": [
    {
     "expr": "geth_txpool_status_queued{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Latest Block",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "geth_latest_block{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Block Number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "geth_latest_block{job=\"block\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}